routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/home','AdminController@dashboard');

Route::get('/users','AdminController@users');

Route::get('/sedi','AdminController@sedi');

Route::get('/records','AdminController@records');

Route::get('/pagamenti','AdminController@pagamenti');

Route::get('/liquidazioni','AdminController@liquidazioni');

Route::get('/user/index','UserController@index');
Route::get('/user/create','UserController@create');
Route::post('/user/store','UserController@store');
Route::get('/user/edit/{id}','UserController@edit');
Route::patch('/user/update/{id}','UserController@update');
Route::post('/user/show','UserController@show');
Route::post('/user/ajax/show','UserController@ajaxShow');



Route::get('/sede/index','SedeController@index');
Route::get('/sede/create','SedeController@create');
Route::post('/sede/store','SedeController@store');
Route::get('/sede/edit/{sede}','SedeController@edit');
Route::patch('/sede/update/{sede}','SedeController@update');
Route::post('/sede/ajax/show','SedeController@ajaxShow');


Route::get('/record/index','RecordController@index');
Route::get('/record/create','RecordController@create');
Route::post('/record/store','RecordController@store');
Route::get('/record/edit/{record}','RecordController@edit');
Route::patch('/record/update/{record}','RecordController@update');
Route::post('/record/ajax/show','RecordController@ajaxShow');
Route::post('/record/import/xls','RecordController@readXls');

Route::get('/pagamento/index','PagamentoController@index');
Route::get('/pagamento/create','PagamentoController@create');
Route::post('/pagamento/store','PagamentoController@store');
Route::get('/pagamento/edit/{pagamento}','PagamentoController@edit');
Route::patch('/pagamento/update/{pagamento}','PagamentoController@update');
Route::post('/pagamento/ajax/show','PagamentoController@ajaxShow');


Route::get('/ajax/riepilogo/quote','AdminController@riepilogoQuote');



Route::get('/liquidazione/index','LiquidatoController@index');
Route::get('/liquidazione/create','LiquidatoController@create');
Route::post('/liquidazione/store','LiquidatoController@store');
Route::get('/liquidazione/edit/{record}','LiquidatoController@edit');
Route::patch('/liquidazione/update/{record}','LiquidatoController@update');
Route::post('/liquidazione/ajax/show','LiquidatoController@ajaxShow');

Route::post('/liquidazione/calcola','LiquidatoController@calcola');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/password',function(){
    $users = \App\User::all();
    foreach ($users as $user){
        if (!Hash::check('2018', $user->password)) {
            $user->update(['password' => \Illuminate\Support\Facades\Hash::make($user->password)]);
        }
    }
});

app/Record.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Record extends Model
{
    //
    protected $fillable = [ 'sindacato',
                            'federazione',
                            'codice_sede',
                            'sede_in_chiaro',
                            'tipo_presentazione',
                            'nome_cognome',
                            'codice_fiscale',
                            'data_nascita',
                            'importo_trattenuta',
                            'data_valuta',
                            'data_pagamento',
                            'numero_domande',
                            'comune_residenza',
                            'codice_patronato',
                            'ufficio_patronato',
                            'patronato'];

    protected $dates = ['data_nascita','data_valuta','data_pagamento'];

    public function users(){
        return $this->hasMany(Addetto::class,'ufficio_patronato','record_id');
    }

    public function getNomeAttribute(){
        $array = explode("/",$this->nome_cognome);
        return $array[1];
    }

    public function getCognomeAttribute(){
        $array = explode("/",$this->nome_cognome);
        return $array[0];
    }

    public function liquidato()
    {
        return $this->morphMany(LiquidatoBody::class, 'attachable');
    }

}

resources/views/admin/dashboard.blade.php
@extends('layouts.dashboardAdmin')
@section('page_heading','Admin Dashboard')
@section('head')
    <link rel="stylesheet" href="{{url('js/tablesorter-master/addons/pager/jquery.tablesorter.pager.css')}}">
    <link rel="stylesheet" href="{{url('js/tablesorter-master/css/theme.blue.css')}}">
    <style>
        .cell_padding_1{
            padding:2px !important;
        }

        .pagination a{
            padding:6px 6px !important;
        }
    </style>
@endsection
@section('section')

    <div class="row">
        <div class="col-sm-12 riepilogo">
            <div class="table-responsive">
                <table class="tablesorter table table-striped">
                    <thead>
                        <tr>
                            <th class="select-find">Responsabile</th>
                            <th class="select-find">Referente</th>
                            <th class="select-find">Sede</th>
                            <th>Codice</th>
                            <th class="select-find">Tipo Sede</th>
                            <th>Quote</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th class="input-find"></th>
                            <th></th>
                            <th class="container_quote"></th>
                        </tr>
                    </tfoot>
                    <tbody>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
@stop

@section('script')

    <link href="{{url('js/datatables.css')}}" rel="stylesheet"/>
    <script src="{{url('js/datatables.js')}}"></script>
    <script>
        $(document).ready(function() {
            var table = $('.tablesorter').DataTable({
                "ajax": '{{url('admin/ajax/riepilogo/quote')}}',
                "language": {
                    "sEmptyTable":     "Nessun dato presente nella tabella",
                    "sInfo":           "Da _START_ a _END_ di _TOTAL_",
                    "sInfoEmpty":      "Da 0 a 0 di 0",
                    "sInfoFiltered":   "(filtrati da _MAX_ elementi totali)",
                    "sInfoPostFix":    "",
                    "sInfoThousands":  ",",
                    "sLengthMenu":     "Visualizza _MENU_ elementi",
                    "sLoadingRecords": "Caricamento...",
                    "sProcessing":     "Elaborazione...",
                    "sSearch":         "Cerca:",
                    "sZeroRecords":    "La ricerca non ha portato alcun risultato.",
                    "oPaginate": {
                        "sFirst":      "Inizio",
                        "sPrevious":   "<<",
                        "sNext":       ">>",
                        "sLast":       "Fine"
                    },
                    "oAria": {
                        "sSortAscending":  ": attiva per ordinare la colonna in ordine crescente",
                        "sSortDescending": ": attiva per ordinare la colonna in ordine decrescente"
                    }
                },
                "columns": [
                    { className: "cell_padding_1" },
                    { className: "cell_padding_1" },
                    { className: "cell_padding_1" },
                    { className: "cell_padding_1" },
                    { className: "cell_padding_1" },
                    { className: "cell_padding_1 cell_quota text-center" }
                ],
                "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
                initComplete: function () {
                    this.api().columns('.select-find').every( function () {
                        var column = this;
                        var select = $('<select class="form-control" style="width:100%; padding:1px; height: auto;"><option value=""></option></select>')
                            .appendTo( $(column.footer()).empty() )
                            .on( 'change', function () {
                                var val = $.fn.dataTable.util.escapeRegex(
                                    $(this).val()
                                );
                                column
                                    .search( val ? '^'+val+'$' : '', true, false )
                                    .draw();
                            });

                        column.data().unique().sort().each( function ( d, j ) {
                            select.append( '<option value="'+d+'">'+d+'</option>' )
                        });
                    } );
                    sum_quote();

                    $('.tablesorter tfoot .input-find').each( function () {
                        var title = $(this).text();
                        $(this).html( '<input type="text" class="form-control" style="width:100%; padding:0px; height: auto;" '+title+'" />' );
                    } );

                    this.api().columns().every( function () {
                        var that = this;
                        $( 'input', this.footer() ).on( 'keyup change', function () {
                            if ( that.search() !== this.value ) {
                                that
                                    .search( this.value )
                                    .draw();
                            }
                        } );
                    } );

                }
            });





        });




        function sum_quote(){
            $(".container_quote").html(0);
            var quote = 0;
            $('.tablesorter').find('tbody').find(".cell_quota").each(function(){
                var value = +$(this).html();
                quote += value;
            });
            $(".container_quote").html(quote);
        }

        $(".riepilogo").on('change',function () {
            sum_quote();

        });

        $(".riepilogo").on('click',function () {
            sum_quote();
        });

    </script>
@stop

resources/views/admin/records.blade.php
@extends('layouts.dashboardAdmin')
@section('page_heading','Amministrazione Addetti')
@section('section')
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Nome</th>
            <th>Cognome</th>
            <th>E-Mail</th>
            <th>Referente</th>
            <th>Quota</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @forelse($records as $record)
            <tr>
                <td>{{$record->nome}}</td>
                <td>{{$record->cognome}}</td>
                <td>{{$record->email}}</td>
                <td>{{$record->referente}}</td>
                <td>{{$record->quota}}</td>
                <td>
                    <a href="" class="btn btn-info"><i class="fa fa-info"></i></a>
                    <a href="" class="btn btn-warning"><i class="fa fa-pencil"></i></a>
                </td>
            </tr>
        @empty
            <tr class="table-warning">
                <td colspan="20" >Nessun record</td>
            </tr>
        @endforelse
        </tbody>
    </table>
    {{ $records->links() }}
@stop